title: کافه قاصدک
description: جایی برای نوشته‌ها، خاطره‌ها و فنجان‌های قهوه
lang: fa
url: "https://sasanfar.github.io"
baseurl: "/cafe-ghasedak"
markdown: kramdown

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
